global:
  smtp_require_tls: false

templates:
- '/etc/alertmanager/*.tmpl'
# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-emailer

  group_by: ['alertname', 'priority']

receivers:
- name: alert-emailer
  email_configs:
  - to: 'customer@example.com'
    send_resolved: false
    from: 'alerting@example.com'
    smarthost: 'mailhog:1025'
    auth_username: 'sender@example.com'