# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    region: 'test'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'dotcms-server'
    static_configs:
      - targets: ['dotcms:9100']
  - job_name: 'nginx-server'
    static_configs:
      - targets: ['nginx:9100']
  - job_name: 'nginx-metrics'
    static_configs:
      - targets: ['nginx:9145']
  - job_name: 'grafana-server'
    static_configs:
      - targets: ['grafana:9100']
  - job_name: 'postgres-server'
    static_configs:
      - targets: ['postgres:9100']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['db-exporter:9187']
  - job_name: 'elasticsearch-server'
    static_configs:
      - targets: ['elasticsearch:9100']
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  - job_name: 'jmx-exporter'
    static_configs:
      - targets: ['jmx-exporter:5556']